# Generated by Django 4.1.3 on 2022-11-03 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_alter_flavor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user_session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(related_name='products', to='product.product')),
            ],
            options={
                'db_table': 'carts',
                'ordering': ('user_session',),
            },
        ),
    ]
