# Generated by Django 4.1.3 on 2022-11-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_flavors'),
        ('cart', '0002_alter_cart_options_cart_created_at_cart_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_bags', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_bag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.cartbag'),
            preserve_default=False,
        ),
    ]
