# Generated by Django 4.1.3 on 2022-11-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartbag_cart_cart_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.cartbag'),
        ),
    ]
