# Generated by Django 4.1.3 on 2022-11-07 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_flavors'),
        ('cart', '0004_alter_cart_cart_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_bag',
        ),
        migrations.AddField(
            model_name='cartbag',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartbag',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
