# Generated by Django 4.1.3 on 2022-11-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_cart_bag_cartbag_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbag',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_bag', to='cart.cart'),
        ),
    ]
