# Generated by Django 4.1.3 on 2022-11-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_categoria_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preco',
            new_name='price',
        ),
    ]
