# Generated by Django 4.1.3 on 2022-11-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
