# Generated by Django 4.1.3 on 2022-11-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image_name',
        ),
    ]
