# Generated by Django 4.1.3 on 2022-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_images_product_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
