# Generated by Django 4.1.3 on 2022-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_flavor_alter_product_category_flavor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(related_name='flavors', to='product.flavor'),
        ),
    ]
