# Generated by Django 4.1.3 on 2022-11-03 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_flavor_product_product_flavors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavor',
            options={'ordering': ('name',)},
        ),
    ]
