# Generated by Django 4.1.3 on 2022-11-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(null=True, related_name='flavors', to='product.flavor'),
        ),
    ]
