# Generated by Django 4.1.3 on 2022-11-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_flavors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, null=True, related_name='flavors', to='product.flavor'),
        ),
    ]
